# Generated by Django 4.2.13 on 2026-06-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono Base')),
                ('nombres', models.CharField(blank=True, max_length=100, verbose_name='Nombres Base')),
                ('paterno', models.CharField(blank=True, max_length=50, verbose_name='Paterno Base')),
                ('materno', models.CharField(blank=True, max_length=50, verbose_name='Materno Base')),
                ('correo', models.EmailField(blank=True, max_length=150, verbose_name='Correo Base')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='Documento Base')),
                ('numero_base', models.CharField(blank=True, max_length=50, verbose_name='Número Base')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Base')),
                ('contact_callable', models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Sí')], max_length=1)),
                ('ultimo_intento', models.CharField(blank=True, max_length=50)),
                ('ultimo_resultado_crm', models.CharField(blank=True, max_length=100)),
                ('es_callable', models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Sí')], max_length=1)),
                ('fecha_gestion', models.DateField(blank=True, null=True)),
                ('hora_gestion', models.TimeField(blank=True, null=True)),
                ('resultado_gestion', models.CharField(blank=True, max_length=100)),
                ('tipo_contacto', models.CharField(blank=True, max_length=50)),
                ('tipo_valido', models.CharField(blank=True, choices=[('Válido', 'Válido'), ('Inválido', 'Inválido'), ('', 'No definido')], max_length=10)),
                ('status_java', models.CharField(blank=True, max_length=50)),
                ('supervisor_nombre', models.CharField(blank=True, max_length=150)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base de Llamada',
                'verbose_name_plural': 'Bases de Llamadas',
                'db_table': 'discador_base',
                'ordering': ['-creado'],
            },
        ),
    ]
