# Generated by Django 4.2.13 on 2026-06-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basellamada',
            name='contact_callable',
            field=models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Sí')], max_length=1, verbose_name='Contacto Llamable'),
        ),
        migrations.AlterField(
            model_name='basellamada',
            name='documento',
            field=models.CharField(blank=True, help_text='DNI, RUT o identificación', max_length=20, verbose_name='Documento Base'),
        ),
        migrations.AlterField(
            model_name='basellamada',
            name='es_callable',
            field=models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Sí')], max_length=1, verbose_name='Es Callable'),
        ),
        migrations.AlterField(
            model_name='basellamada',
            name='fecha_gestion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Gestión'),
        ),
        migrations.AlterField(
            model_name='basellamada',
            name='hora_gestion',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Gestión'),
        ),
        migrations.AlterField(
            model_name='basellamada',
            name='resultado_gestion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Resultado de Gestión'),
        ),
        migrations.AlterField(
            model_name='basellamada',
            name='status_java',
            field=models.CharField(blank=True, max_length=50, verbose_name='Status JAVA'),
        ),
        migrations.AlterField(
            model_name='basellamada',
            name='supervisor_nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='basellamada',
            name='tipo_contacto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de Contacto'),
        ),
        migrations.AlterField(
            model_name='basellamada',
            name='tipo_valido',
            field=models.CharField(blank=True, choices=[('Válido', 'Válido'), ('Inválido', 'Inválido'), ('', 'No definido')], max_length=10, verbose_name='Tipo Válido'),
        ),
        migrations.AlterField(
            model_name='basellamada',
            name='ultimo_intento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Último Intento (CRM)'),
        ),
        migrations.AlterField(
            model_name='basellamada',
            name='ultimo_resultado_crm',
            field=models.CharField(blank=True, max_length=100, verbose_name='Último Resultado (CRM)'),
        ),
    ]
