# Generated by Django 4.2.13 on 2026-06-03 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discador', '0002_alter_basellamada_contact_callable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('CONTESTADA', 'Contestada'), ('NO_CONTESTADA', 'No contestada'), ('OCUPADA', 'Ocupada'), ('DESCONECTADA', 'Desconectada'), ('NO_VOZ', 'No voz'), ('FAX', 'Fax'), ('OTRO', 'Otro')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to=settings.AUTH_USER_MODEL)),
                ('base_llamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='discador.basellamada')),
            ],
            options={
                'verbose_name': 'Registro de Llamada',
                'verbose_name_plural': 'Registros de Llamadas',
                'ordering': ['-inicio'],
            },
        ),
    ]
