# Generated by Django 4.2.13 on 2026-06-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0003_callrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='acw_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de ACW'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='acw_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de ACW'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='disposition',
            field=models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('NO_CONTESTA', 'No contesta'), ('CUELGA', 'Cuelga'), ('FAX', 'Fax'), ('NO_DESEA', 'No desea'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipificación'),
        ),
    ]
