# Generated by Django 4.2.13 on 2026-06-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0004_callrecord_acw_end_callrecord_acw_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='liberado_sin_uso',
            field=models.BooleanField(default=False, verbose_name='Liberado sin uso'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='disposition',
            field=models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('NO_CONTESTA', 'No contesta'), ('CUELGA', 'Cuelga'), ('FAX', 'Fax'), ('NO_DESEA', 'No desea'), ('OTRO', 'Otro'), ('LIBERADO_SIN_USO', 'Liberado sin uso')], max_length=20, verbose_name='Tipificación'),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='resultado',
            field=models.CharField(choices=[('CONTESTADA', 'Contestada'), ('NO_CONTESTADA', 'No contestada'), ('OCUPADA', 'Ocupada'), ('DESCONECTADA', 'Desconectada'), ('NO_VOZ', 'No voz'), ('FAX', 'Fax'), ('OTRO', 'Otro'), ('LIBERADO_SIN_USO', 'Liberado sin uso')], max_length=20),
        ),
    ]
