# Generated by Django 4.2.13 on 2026-06-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0006_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basellamada',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
