# Generated by Django 4.2.13 on 2026-06-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0008_callrecord_resultado_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='basellamada',
            name='base_manual',
            field=models.BooleanField(default=False, help_text='Marcar si el número NO existe en una base y es lead cargado manualmente', verbose_name='Lead Manual'),
        ),
        migrations.AddField(
            model_name='basellamada',
            name='base_procedencia',
            field=models.CharField(blank=True, choices=[('POT', 'POT'), ('RSG_01', 'RSG_01')], db_index=True, default='', max_length=20, verbose_name='Base de Procedencia'),
        ),
    ]
