# Generated by Django 5.2.15 on 2026-06-20 18:16

import apps.discador.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0010_add_venta_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basellamada',
            name='id_lead',
            field=apps.discador.models.HexUUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Lead'),
        ),
    ]
