# Generated by Django 4.2.13 on 2026-06-07 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0014_venta_tipo_via'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_bo', models.CharField(blank=True, choices=[('EN_BASE', 'En Base'), ('PDTE_BO', 'Pdte. BO'), ('EN_BO', 'En BO'), ('VALIDADO', 'Validado'), ('EN_DESPACHO', 'En Despacho'), ('DESPACHADO', 'Despachado')], default='PDTE_BO', max_length=30)),
                ('fecha_bo', models.DateField(blank=True, null=True, verbose_name='Fecha BO')),
                ('supervisor', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bo_seguimiento', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Seguimiento BO',
                'verbose_name_plural': 'Seguimientos BO',
                'db_table': 'postventa_seguimientobo',
                'ordering': ['-creado'],
            },
        ),
    ]