# Generated by Django 4.2.13 on 2026-06-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0014_venta_tipo_via'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'postventa_proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_bo', models.CharField(blank=True, choices=[('EN_BASE', 'En Base'), ('PDTE_BO', 'Pdte. BO'), ('EN_BO', 'En BO'), ('VALIDADO', 'Validado'), ('EN_DESPACHO', 'En Despacho'), ('DESPACHADO', 'Despachado')], default='PDTE_BO', max_length=30)),
                ('fecha_bo', models.DateField(blank=True, null=True, verbose_name='Fecha BO')),
                ('supervisor', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_bo', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Seguimiento BO',
                'verbose_name_plural': 'Seguimientos BO',
                'db_table': 'postventa_seguimientobo',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='EstadoDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(blank=True, choices=[('EN_BASE', 'En Base'), ('PDTE_DESPACHO', 'Pdte. Despacho'), ('EN_PREPARACION', 'En Preparación'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], default='EN_BASE', max_length=30)),
                ('fecha_etapa', models.DateField(blank=True, null=True)),
                ('tracking', models.CharField(blank=True, max_length=100, verbose_name='N° Seguimiento / Tracking')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to='postventa.proveedor')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_despacho', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Estado Despacho',
                'verbose_name_plural': 'Estados Despacho',
                'db_table': 'postventa_estadodespacho',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sts_courier', models.CharField(blank=True, choices=[('PDTE_BO', 'Pdte. BO'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], default='PDTE_BO', max_length=30)),
                ('fch_courier', models.DateField(blank=True, null=True, verbose_name='Fecha Courier')),
                ('tracking', models.CharField(blank=True, max_length=100, verbose_name='N° Seguimiento / Tracking')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='postventa.proveedor')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_courier', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Estado Courier',
                'verbose_name_plural': 'Estados Courier',
                'db_table': 'postventa_estadocourier',
                'ordering': ['-creado'],
            },
        ),
    ]
