# Generated by Django 4.2.13 on 2026-06-02 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_agente', models.CharField(max_length=20, unique=True, verbose_name='Código de Agente')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('supervisor', models.CharField(blank=True, max_length=150, verbose_name='Supervisor Asignado')),
                ('zona', models.CharField(blank=True, max_length=100, verbose_name='Zona de Trabajo')),
                ('turno', models.CharField(blank=True, max_length=50, verbose_name='Turno')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'users_profile',
            },
        ),
    ]
