# Generated by Django 4.2.13 on 2026-06-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('AGENTE', 'Agente'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Administrador')], default='AGENTE', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='codigo_agente',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Agente'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentes_supervisados', to='users.userprofile', verbose_name='Supervisor Asignado'),
        ),
    ]
