# Generated by Django 4.2.13 on 2026-06-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_rol_alter_userprofile_codigo_agente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PAUSA', 'Pausa'), ('LISTO_NO', 'Listo No'), ('COACH', 'Coach')], default='DISPONIBLE', max_length=20, verbose_name='Estado'),
        ),
    ]
