# Generated by Django 4.2.13 on 2026-06-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='turno',
            field=models.CharField(blank=True, choices=[('DIURNO', 'Diurno'), ('NOCTURNO', 'Nocturno'), ('HIBRIDO', 'Híbrido')], max_length=20, verbose_name='Turno'),
        ),
    ]
