# Generated by Django 4.2.13 on 2026-06-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_estado_alter_userprofile_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BAJA', 'Baja'), ('VACACIONES', 'Vacaciones')], default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disponibilidad',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PAUSA', 'Pausa'), ('LISTO_NO', 'No Listo'), ('EN_LLAMADA', 'En Llamada'), ('COACH', 'Coach')], default='DISPONIBLE', max_length=20, verbose_name='Disponibilidad'),
        ),
    ]