# Generated by Django 4.2.13 on 2026-06-07 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0014_venta_tipo_via'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor Courier',
                'verbose_name_plural': 'Proveedores Courier',
                'db_table': 'courier_proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sts_courier', models.CharField(blank=True, choices=[('PDTE_BO', 'Pdte. BO'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], default='PDTE_BO', max_length=30)),
                ('fch_courier', models.DateField(blank=True, null=True, verbose_name='Fecha Courier')),
                ('tracking', models.CharField(blank=True, max_length=100, verbose_name='N° Seguimiento / Tracking')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='courier.proveedorcourier')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_estado', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Estado Courier',
                'verbose_name_plural': 'Estados Courier',
                'db_table': 'courier_estado',
                'ordering': ['-creado'],
            },
        ),
    ]