# Generated by Django 4.2.13 on 2026-06-07 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0014_venta_tipo_via'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor Despacho',
                'verbose_name_plural': 'Proveedores Despacho',
                'db_table': 'despacho_proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(blank=True, choices=[('EN_BASE', 'En Base'), ('PDTE_DESPACHO', 'Pdte. Despacho'), ('EN_PREPARACION', 'En Preparación'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], default='EN_BASE', max_length=30)),
                ('fecha_etapa', models.DateField(blank=True, null=True, verbose_name='Fecha Etapa')),
                ('tracking', models.CharField(blank=True, max_length=100, verbose_name='N° Seguimiento / Tracking')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to='despacho.proveedor')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='despacho_estado', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Estado Despacho',
                'verbose_name_plural': 'Estados Despacho',
                'db_table': 'despacho_estado',
                'ordering': ['-creado'],
            },
        ),
    ]