# Generated by Django 4.2.13 on 2026-06-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_nombre', models.CharField(max_length=150, verbose_name='Agente (Vendedor)')),
                ('cliente_nombres', models.CharField(blank=True, max_length=100)),
                ('cliente_paterno', models.CharField(blank=True, max_length=50)),
                ('cliente_materno', models.CharField(blank=True, max_length=50)),
                ('cliente_documento', models.CharField(blank=True, max_length=20)),
                ('cliente_numero', models.CharField(blank=True, max_length=50)),
                ('cliente_telefono_1', models.CharField(blank=True, max_length=20)),
                ('cliente_telefono_2', models.CharField(blank=True, max_length=20)),
                ('recibo_electronico', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('SI_DESEA', 'Si desea'), ('NO_DESEA', 'No desea')], max_length=10)),
                ('correo_electronico_recibo', models.EmailField(blank=True, max_length=150)),
                ('horario_visita', models.CharField(blank=True, max_length=100)),
                ('abdcp', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('clausulas', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('SI_DESEA', 'Si desea'), ('NO_DESEA', 'No desea')], max_length=10)),
                ('producto_nombre', models.CharField(blank=True, max_length=150)),
                ('origen', models.CharField(blank=True, max_length=100)),
                ('operador', models.CharField(blank=True, max_length=50)),
                ('telefono_portar', models.CharField(blank=True, max_length=20)),
                ('modelo_producto', models.CharField(blank=True, max_length=100)),
                ('plan_producto', models.CharField(blank=True, max_length=100)),
                ('tipo_linea', models.CharField(blank=True, choices=[('PREPAGO', 'Prepago'), ('POSTPAGO', 'Postpago'), ('LINEA_NUEVA', 'Línea nueva'), ('PORTABILIDAD', 'Portabilidad')], max_length=20)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tipo_pago', models.CharField(blank=True, max_length=50)),
                ('tipo_via', models.CharField(blank=True, max_length=20)),
                ('nombre_via', models.CharField(blank=True, max_length=150)),
                ('numero_via', models.CharField(blank=True, max_length=20)),
                ('manzana', models.CharField(blank=True, max_length=10)),
                ('interior', models.CharField(blank=True, max_length=10)),
                ('lote', models.CharField(blank=True, max_length=10)),
                ('piso', models.CharField(blank=True, max_length=10)),
                ('zona_tipo', models.CharField(blank=True, max_length=50)),
                ('zona_nombre', models.CharField(blank=True, max_length=150)),
                ('zona_referencia', models.TextField(blank=True)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('distrito', models.CharField(blank=True, max_length=100)),
                ('facturacion_requerida', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('base', models.CharField(blank=True, max_length=50, verbose_name='Base')),
                ('tipo_renta', models.CharField(blank=True, max_length=20)),
                ('tipo_renta2', models.CharField(blank=True, max_length=20)),
                ('base3', models.CharField(blank=True, max_length=50)),
                ('q_ventas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('hora_venta', models.TimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas_venta',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_bo', models.CharField(blank=True, max_length=50)),
                ('fecha_bo', models.DateField(blank=True, null=True)),
                ('sts_courier', models.CharField(blank=True, max_length=50)),
                ('fch_courier', models.DateField(blank=True, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=150)),
                ('intervalo', models.CharField(blank=True, max_length=20)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backoffice', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Seguimiento Backoffice',
                'verbose_name_plural': 'Seguimientos Backoffice',
                'db_table': 'ventas_backoffice',
            },
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venta', models.CharField(blank=True, max_length=50)),
                ('tipo_producto', models.CharField(blank=True, max_length=50)),
                ('precio_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Ítem de Venta',
                'verbose_name_plural': 'Ítems de Venta',
                'db_table': 'ventas_item',
            },
        ),
    ]
