# Generated by Django 4.2.13 on 2026-06-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='venta',
            name='contact_callable',
            field=models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Sí')], max_length=1),
        ),
        migrations.AddField(
            model_name='venta',
            name='es_callable',
            field=models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Sí')], max_length=1),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_gestion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='hora_gestion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='resultado_gestion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='status_java',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='supervisor_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_contacto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_valido',
            field=models.CharField(blank=True, choices=[('Válido', 'Válido'), ('Inválido', 'Inválido'), ('', 'No definido')], max_length=10),
        ),
    ]
