# Generated by Django 4.2.13 on 2026-06-02 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-creado'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='precio_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio del Plan'),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='tipo_producto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de Producto'),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='tipo_venta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de Venta'),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta', verbose_name='Venta'),
        ),
        migrations.AlterField(
            model_name='seguimientobo',
            name='fch_courier',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Courier'),
        ),
        migrations.AlterField(
            model_name='seguimientobo',
            name='fecha_bo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha BO'),
        ),
        migrations.AlterField(
            model_name='seguimientobo',
            name='intervalo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Intervalo'),
        ),
        migrations.AlterField(
            model_name='seguimientobo',
            name='status_bo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Status BO'),
        ),
        migrations.AlterField(
            model_name='seguimientobo',
            name='sts_courier',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sts Courier'),
        ),
        migrations.AlterField(
            model_name='seguimientobo',
            name='supervisor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='seguimientobo',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backoffice', to='ventas.venta', verbose_name='Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='abdcp',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='ABDCP'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='base3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Base3'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='clausulas',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('SI_DESEA', 'Si desea'), ('NO_DESEA', 'No desea')], max_length=10, verbose_name='Cláusulas'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='contact_callable',
            field=models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Sí')], max_length=1, verbose_name='Contacto Llamable (disc.)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='correo_electronico_recibo',
            field=models.EmailField(blank=True, max_length=150, verbose_name='Correo Electrónico (Recibo)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='es_callable',
            field=models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Sí')], max_length=1, verbose_name='Es Callable (disc.)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='facturacion_requerida',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='¿Requiere Factura?'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_gestion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Gestión (disc.)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='hora_gestion',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Gestión (disc.)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='hora_venta',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='horario_visita',
            field=models.CharField(blank=True, max_length=100, verbose_name='Horario de Visita'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='interior',
            field=models.CharField(blank=True, max_length=10, verbose_name='Interior'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='lote',
            field=models.CharField(blank=True, max_length=10, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='manzana',
            field=models.CharField(blank=True, max_length=10, verbose_name='Manzana'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='modelo_producto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo Producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombre_via',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre de Vía'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_via',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de Vía'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='operador',
            field=models.CharField(blank=True, max_length=50, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='origen',
            field=models.CharField(blank=True, max_length=100, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='piso',
            field=models.CharField(blank=True, max_length=10, verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='plan_producto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Plan Producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio del Plan'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto_nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='q_ventas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de Ventas'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='resultado_gestion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Resultado Gestión (disc.)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='status_java',
            field=models.CharField(blank=True, max_length=50, verbose_name='Status JAVA (disc.)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='supervisor_nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Supervisor (disc.)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='telefono_portar',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono a Portar'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_contacto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo Contacto (disc.)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_linea',
            field=models.CharField(blank=True, choices=[('PREPAGO', 'Prepago'), ('POSTPAGO', 'Postpago'), ('LINEA_NUEVA', 'Línea nueva'), ('PORTABILIDAD', 'Portabilidad')], max_length=20, verbose_name='Tipo de Línea'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_renta',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo Renta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_renta2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo Renta 2'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_valido',
            field=models.CharField(blank=True, choices=[('Válido', 'Válido'), ('Inválido', 'Inválido'), ('', 'No definido')], max_length=10, verbose_name='Tipo Válido (disc.)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_via',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de Vía'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='zona_nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre de Zona'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='zona_referencia',
            field=models.TextField(blank=True, verbose_name='Referencia de Zona'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='zona_tipo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de Zona'),
        ),
    ]
