# Generated by Django 4.2.13 on 2026-06-02 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_venta_options_alter_itemventa_precio_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('paterno', models.CharField(blank=True, max_length=50, verbose_name='Paterno')),
                ('materno', models.CharField(blank=True, max_length=50, verbose_name='Materno')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Número')),
                ('telefono_1', models.CharField(blank=True, max_length=20, verbose_name='Teléfono 01')),
                ('telefono_2', models.CharField(blank=True, max_length=20, verbose_name='Teléfono 02')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'ventas_cliente',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.cliente', verbose_name='Cliente'),
        ),
    ]
