# Generated by Django 4.2.13 on 2026-06-03 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0002_alter_basellamada_contact_callable_and_more'),
        ('ventas', '0005_cliente_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='base_llamada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discador.basellamada', verbose_name='Base Llamada'),
        ),
    ]
