# Generated by Django 4.2.13 on 2026-06-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_base_llamada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente_numero',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet de Extranjería'), ('PASAPORTE', 'Pasaporte')], default='DNI', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet de Extranjería'), ('PASAPORTE', 'Pasaporte')], default='DNI', max_length=20, verbose_name='Tipo de Documento'),
        ),
    ]
