# Generated by Django 4.2.13 on 2026-06-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_remove_cliente_numero_remove_venta_cliente_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='clausulas',
            field=models.CharField(blank=True, choices=[('SI_DESEA', 'Si desea'), ('NO_DESEA', 'No desea')], max_length=10, verbose_name='Cláusulas'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='horario_visita',
            field=models.CharField(blank=True, choices=[('LUNES_8_12', 'Lunes a Viernes 8am – 12pm'), ('LUNES_13_17', 'Lunes a Viernes 1pm – 5pm'), ('LUNES_17_20', 'Lunes a Viernes 5pm – 8pm (express)'), ('SABADO_8_13', 'Sábado 8am – 1pm')], max_length=20, verbose_name='Horario de Visita'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='recibo_electronico',
            field=models.CharField(blank=True, choices=[('SI_DESEA', 'Si desea'), ('NO_DESEA', 'No desea')], max_length=10, verbose_name='Recibo Electrónico'),
        ),
    ]
