# Generated by Django 4.2.13 on 2026-06-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_venta_tipo_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='departamento',
            field=models.CharField(blank=True, choices=[('', 'Seleccione departamento'), ('AMAZONAS', 'Amazonas'), ('ANCASH', 'Ancash'), ('APURIMAC', 'Apurímac'), ('AREQUIPA', 'Arequipa'), ('AYACUCHO', 'Ayacucho'), ('CAJAMARCA', 'Cajamarca'), ('CALLAO', 'Callao'), ('CUSCO', 'Cusco'), ('HUANCAYO', 'Huancayo'), ('HUÁNUCO', 'Huánuco'), ('ICA', 'Ica'), ('JUNIN', 'Junín'), ('LA_LIBERTAD', 'La Libertad'), ('LAMBAYEQUE', 'Lambayeque'), ('LIMA', 'Lima'), ('LORETO', 'Loreto'), ('MADRE_DE_DIOS', 'Madre de Dios'), ('PASCO', 'Pasco'), ('PIURA', 'Piura'), ('PUNO', 'Puno'), ('SAN_MARTIN', 'San Martín'), ('TACNA', 'Tacna'), ('TUMBES', 'Tumbes'), ('UCAYALI', 'Ucayali')], max_length=100, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, verbose_name='Distrito'),
        ),
    ]