# Generated by Django 4.2.13 on 2026-06-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_remove_discador_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='multiples_lineas',
            field=models.BooleanField(default=False, help_text='Marcar cuando la venta incluye más de una línea (activa tipo_renta2)', verbose_name='Venta multilínea'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_renta2',
            field=models.CharField(blank=True, help_text='Calculado igual que tipo_renta, pero para la segunda línea o línea adicional', max_length=20, verbose_name='Tipo Renta Multilínea'),
        ),
    ]
