# Generated by Django 4.2.13 on 2026-06-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_venta_multiples_lineas_venta_tipo_via_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_via',
            field=models.CharField(blank=True, choices=[('AVENIDA', 'Avenida (Av.)'), ('CALLE', 'Calle (Cl.)'), ('JIRON', 'Jirón (Jr.)'), ('PASAJE', 'Pasaje (Psj.)'), ('PROLONGACION', 'Prolongación (Prol.)'), ('CARRETERA', 'Carretera (Carr.)'), ('MALECON', 'Malecón (Mal.)'), ('ALAMEDA', 'Alameda (Al.)'), ('URBANIZACION', 'Urbanización (Urb.)'), ('ASOCIACION', 'Asociación (AA.HH.)'), ('PUEBLO_JOVEN', 'Pueblo Joven (P.J.)')], max_length=20, verbose_name='Tipo de Vía'),
        ),
    ]
