# Generated by Django 4.2.13 on 2026-06-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_venta_tipo_via'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeguimientoBO',
        ),
    ]
