# Generated by Django 4.2.13 on 2026-06-08 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_remove_old_seguimientobo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='base_llamada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_asociadas', to='discador.basellamada', verbose_name='Base Llamada'),
        ),
    ]
