# Generated by Django 4.2.13 on 2026-06-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_add_related_name_base_llamada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemventa',
            name='precio_plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio del Plan'),
        ),
    ]
