# Generated by Django 4.2.13 on 2026-06-10
# Remove transitory fields: base3, q_ventas
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_alter_itemventa_precio_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='base3',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='q_ventas',
        ),
    ]